version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - ~/graylog/data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ~/graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: "graylog2/server"
    volumes:
      - ~/graylog/data/journal:/usr/share/graylog/data/journal
      - ~/graylog/config:/usr/share/graylog/data/config
    environment:
      # GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:9000/api/" # didn't like having this config here (tried looking for REST server at this address) - could be a bug
      #
      # NOTE - your salt needs to be different
      #
      GRAYLOG_PASSWORD_SECRET: A_SALT_HERE
      #
      # NOTE - your hash needs to be different
      #
      GRAYLOG_ROOT_PASSWORD_SHA2: A_BIG_HASH_HERE
      GRAYLOG_REST_TRANSPORT_URI: "http://YOUR_PUBLIC_EC2_IP_ADDRESS_HERE:12900"
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12900:12900"
      - "5555:5555"